In [3]:
%pip install kafka-python

Requirement already satisfied: kafka-python in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (2.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from kafka import KafkaProducer

producer = KafkaProducer(bootstrap_servers="localhost:9092")
producer.send("test_topic", b"hello from jupyter")
producer.flush()
print("Sent from Jupyter")

Sent from Jupyter ✅

In [5]:
from kafka import KafkaProducer
producer = KafkaProducer(bootstrap_servers="localhost:9092")
producer.send("test_topic", b"message test: spark is reading kafka")
producer.flush()
print("Sent to Kafka")

Sent to Kafka

In [6]:
producer.send("test_topic", b"spark reads kafka now")
producer.flush()

In [7]:
from kafka import KafkaProducer
producer = KafkaProducer(bootstrap_servers="localhost:9092")

for i in range(3):
    producer.send("test_topic", f"parquet test message {i}".encode("utf-8"))
producer.flush()

print("3 messages sent")

3 messages sent

In [8]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (21.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

(['data/parquet_windows\\part-00000-0ea75ecd-9e07-4231-833f-a71fefa749e1-c000.snappy.parquet',
  'data/parquet_windows\\part-00000-9898e32a-4698-4694-b800-8e46dd617204-c000.snappy.parquet'],
 2)

In [1]:
import pandas as pd
import glob

files = glob.glob("data/parquet_windows/*.parquet")
files[:3], len(files)

(['data/parquet_windows\\part-00000-0ea75ecd-9e07-4231-833f-a71fefa749e1-c000.snappy.parquet',
  'data/parquet_windows\\part-00000-9898e32a-4698-4694-b800-8e46dd617204-c000.snappy.parquet'],
 2)

In [3]:
import pandas as pd
df = pd.read_parquet("data/parquet_windows")
df.head()

                  message              event_time
0  parquet test message 0 2026-01-19 00:18:48.425
1  parquet test message 1 2026-01-19 00:18:48.425
2  parquet test message 2 2026-01-19 00:18:48.425

In [1]:
!pip install -q pyarrow pandas

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df["message"].value_counts().head(20)

message
parquet test message 0    1
parquet test message 1    1
parquet test message 2    1
Name: count, dtype: int64

In [5]:
import json, time
from kafka import KafkaProducer

producer = KafkaProducer(
    bootstrap_servers="localhost:9092",
    value_serializer=lambda v: json.dumps(v).encode("utf-8")
)

source_id = "cam_01"
events = [
    {"source_id": source_id, "emotion": "happy", "score": 0.93},
    {"source_id": source_id, "emotion": "neutral", "score": 0.72},
    {"source_id": source_id, "emotion": "sad", "score": 0.81},
    {"source_id": source_id, "emotion": "happy", "score": 0.95},
]

for e in events:
    e["event_time"] = time.strftime("%Y-%m-%d %H:%M:%S")
    producer.send("test_topic", e)
    time.sleep(0.3)

producer.flush()
print("✅ JSON events sent")

✅ JSON events sent

In [6]:
import pandas as pd
df2 = pd.read_parquet("data/parquet_events")
df2.head()

Empty DataFrame
Columns: [source_id, event_time, emotion, score]
Index: []

In [7]:
df2["emotion"].value_counts()

Series([], Name: count, dtype: int64)

In [8]:
import json, time
from kafka import KafkaProducer

producer = KafkaProducer(
    bootstrap_servers="localhost:9092",
    value_serializer=lambda v: json.dumps(v).encode("utf-8")
)

for i, emo in enumerate(["happy", "neutral", "sad", "happy", "angry"]):
    event = {
        "source_id": "cam_01",
        "event_time": time.strftime("%Y-%m-%d %H:%M:%S"),
        "emotion": emo,
        "score": round(0.6 + 0.1*i, 2)
    }
    producer.send("test_topic", event)
    time.sleep(0.2)

producer.flush()
print("✅ JSON events sent")

✅ JSON events sent

In [9]:
import pandas as pd
df_events = pd.read_parquet("data/parquet_events")
df_events.head()

  source_id           event_time  emotion  score
0    cam_01  2026-02-12 00:02:16    happy    0.6
1    cam_01  2026-02-12 00:02:17  neutral    0.7
2    cam_01  2026-02-12 00:02:17      sad    0.8
3    cam_01  2026-02-12 00:02:17    happy    0.9
4    cam_01  2026-02-12 00:02:17    angry    1.0

In [11]:
!pip install streamlit pandas pyarrow

Collecting streamlit
  Downloading streamlit-1.54.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: pandas in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: pyarrow in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (21.0.0)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<7,>=5.5 (from streamlit)
  Downloading cachetools-6.2.6-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.3.0)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging>=20 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (12.0.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.33.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.5.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
     ---------------------------------------- 0.0/44.3 kB ? eta -:--:--
     ---------------------------------------- 44.3/44.3 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: jinja2 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.27.1 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.8.0)
Requirement already satisfied: colorama in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.10.5)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\youssouf djire\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.27.1)
Downloading streamlit-1.54.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
    --------------------------------------- 0.1/9.1 MB 3.5 MB/s eta 0:00:03
    --------------------------------------- 0.1/9.1 MB 3.5 MB/s eta 0:00:03
    --------------------------------------- 0.2/9.1 MB 2.0 MB/s eta 0:00:05
   - -------------------------------------- 0.3/9.1 MB 2.1 MB/s eta 0:00:05
   - -------------------------------------- 0.4/9.1 MB 1.9 MB/s eta 0:00:05
   - -------------------------------------- 0.5/9.1 MB 1.9 MB/s eta 0:00:05
   -- ------------------------------------- 0.5/9.1 MB 1.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/9.1 MB 1.6 MB/s eta 0:00:06
   -- ------------------------------------- 0.7/9.1 MB 1.8 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/9.1 MB 1.7 MB/s eta 0:00:05
   --- ------------------------------------ 0.9/9.1 MB 1.8 MB/s eta 0:00:05
   --- ------------------------------------ 0.9/9.1 MB 1.8 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/9.1 MB 1.7 MB/s eta 0:00:05
   ---- ----------------------------------- 1.1/9.1 MB 1.7 MB/s eta 0:00:05
   ----- ---------------------------------- 1.1/9.1 MB 1.7 MB/s eta 0:00:05
   ----- ---------------------------------- 1.2/9.1 MB 1.7 MB/s eta 0:00:05
   ----- ---------------------------------- 1.3/9.1 MB 1.7 MB/s eta 0:00:05
   ------ --------------------------------- 1.4/9.1 MB 1.8 MB/s eta 0:00:05
   ------ --------------------------------- 1.5/9.1 MB 1.8 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.1 MB 1.8 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/9.1 MB 1.8 MB/s eta 0:00:05
   ------- -------------------------------- 1.7/9.1 MB 1.8 MB/s eta 0:00:05
   -------- ------------------------------- 1.8/9.1 MB 1.8 MB/s eta 0:00:04
   -------- ------------------------------- 1.9/9.1 MB 1.8 MB/s eta 0:00:04
   -------- ------------------------------- 2.0/9.1 MB 1.8 MB/s eta 0:00:04
   --------- ------------------------------ 2.1/9.1 MB 1.8 MB/s eta 0:00:04
   --------- ------------------------------ 2.2/9.1 MB 1.9 MB/s eta 0:00:04
   --------- ------------------------------ 2.2/9.1 MB 1.9 MB/s eta 0:00:04
   ---------- ----------------------------- 2.4/9.1 MB 1.9 MB/s eta 0:00:04
   ---------- ----------------------------- 2.4/9.1 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.5/9.1 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.6/9.1 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.7/9.1 MB 1.9 MB/s eta 0:00:04
   ------------ --------------------------- 2.8/9.1 MB 1.9 MB/s eta 0:00:04
   ------------ --------------------------- 2.9/9.1 MB 1.9 MB/s eta 0:00:04
   ------------ --------------------------- 2.9/9.1 MB 1.9 MB/s eta 0:00:04
   ------------- -------------------------- 3.0/9.1 MB 1.9 MB/s eta 0:00:04
   ------------- -------------------------- 3.2/9.1 MB 1.9 MB/s eta 0:00:04
   -------------- ------------------------- 3.2/9.1 MB 1.9 MB/s eta 0:00:04
   -------------- ------------------------- 3.4/9.1 MB 1.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.4/9.1 MB 1.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.5/9.1 MB 1.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.6/9.1 MB 1.9 MB/s eta 0:00:03
   ---------------- ----------------------- 3.7/9.1 MB 1.9 MB/s eta 0:00:03
   ---------------- ----------------------- 3.8/9.1 MB 2.0 MB/s eta 0:00:03
   ----------------- ---------------------- 3.9/9.1 MB 1.9 MB/s eta 0:00:03
   ----------------- ---------------------- 3.9/9.1 MB 1.9 MB/s eta 0:00:03
   ----------------- ---------------------- 4.1/9.1 MB 2.0 MB/s eta 0:00:03
   ------------------ --------------------- 4.2/9.1 MB 2.0 MB/s eta 0:00:03
   ------------------ --------------------- 4.3/9.1 MB 2.0 MB/s eta 0:00:03
   ------------------- -------------------- 4.4/9.1 MB 2.0 MB/s eta 0:00:03
   ------------------- -------------------- 4.5/9.1 MB 2.0 MB/s eta 0:00:03
   -------------------- ------------------- 4.6/9.1 MB 2.0 MB/s eta 0:00:03
   -------------------- ------------------- 4.7/9.1 MB 2.0 MB/s eta 0:00:03
   -------------------- ------------------- 4.8/9.1 MB 2.0 MB/s eta 0:00:03
   --------------------- ------------------ 4.9/9.1 MB 2.0 MB/s eta 0:00:03
   --------------------- ------------------ 5.0/9.1 MB 2.0 MB/s eta 0:00:03
   ---------------------- ----------------- 5.1/9.1 MB 2.0 MB/s eta 0:00:03
   ---------------------- ----------------- 5.1/9.1 MB 2.0 MB/s eta 0:00:02
   ----------------------- ---------------- 5.3/9.1 MB 2.0 MB/s eta 0:00:02
   ----------------------- ---------------- 5.3/9.1 MB 2.0 MB/s eta 0:00:02
   ----------------------- ---------------- 5.5/9.1 MB 2.0 MB/s eta 0:00:02
   ------------------------ --------------- 5.5/9.1 MB 2.0 MB/s eta 0:00:02
   ------------------------ --------------- 5.7/9.1 MB 2.0 MB/s eta 0:00:02
   ------------------------- -------------- 5.8/9.1 MB 2.0 MB/s eta 0:00:02
   ------------------------- -------------- 5.8/9.1 MB 2.0 MB/s eta 0:00:02
   -------------------------- ------------- 6.0/9.1 MB 2.0 MB/s eta 0:00:02
   -------------------------- ------------- 6.0/9.1 MB 2.1 MB/s eta 0:00:02
   -------------------------- ------------- 6.2/9.1 MB 2.1 MB/s eta 0:00:02
   --------------------------- ------------ 6.2/9.1 MB 2.1 MB/s eta 0:00:02
   --------------------------- ------------ 6.3/9.1 MB 2.0 MB/s eta 0:00:02
   ---------------------------- ----------- 6.4/9.1 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 6.5/9.1 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 6.7/9.1 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 6.7/9.1 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 6.8/9.1 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 7.0/9.1 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 7.1/9.1 MB 2.1 MB/s eta 0:00:01
   ------------------------------- -------- 7.2/9.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------- ------- 7.3/9.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------- ------- 7.4/9.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------- ------- 7.5/9.1 MB 2.1 MB/s eta 0:00:01
   --------------------------------- ------ 7.6/9.1 MB 2.1 MB/s eta 0:00:01
   --------------------------------- ------ 7.7/9.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 7.8/9.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 7.9/9.1 MB 2.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.0/9.1 MB 2.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.1/9.1 MB 2.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.2/9.1 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 8.3/9.1 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 8.4/9.1 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 8.6/9.1 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 8.7/9.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 8.8/9.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 8.9/9.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  8.9/9.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  9.1/9.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  9.1/9.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 2.1 MB/s eta 0:00:00
Downloading altair-6.0.0-py3-none-any.whl (795 kB)
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ---- ----------------------------------- 92.2/795.4 kB 2.6 MB/s eta 0:00:01
   ------- -------------------------------- 143.4/795.4 kB 2.1 MB/s eta 0:00:01
   ------- -------------------------------- 143.4/795.4 kB 2.1 MB/s eta 0:00:01
   -------- ----------------------------- 174.1/795.4 kB 958.1 kB/s eta 0:00:01
   -------------------- ------------------- 399.4/795.4 kB 1.9 MB/s eta 0:00:01
   ------------------------- -------------- 512.0/795.4 kB 1.9 MB/s eta 0:00:01
   ---------------------------- ----------- 563.2/795.4 kB 1.9 MB/s eta 0:00:01
   -------------------------------- ------- 645.1/795.4 kB 1.9 MB/s eta 0:00:01
   ------------------------------------ --- 727.0/795.4 kB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 768.0/795.4 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------  788.5/795.4 kB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 795.4/795.4 kB 1.6 MB/s eta 0:00:00
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-6.2.6-py3-none-any.whl (11 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
   ---------------------------------------- 0.0/208.6 kB ? eta -:--:--
   --------------------- ------------------ 112.6/208.6 kB 3.3 MB/s eta 0:00:01
   --------------------- ------------------ 112.6/208.6 kB 3.3 MB/s eta 0:00:01
   --------------------- ------------------ 112.6/208.6 kB 3.3 MB/s eta 0:00:01
   ---------------------- --------------- 122.9/208.6 kB 722.1 kB/s eta 0:00:01
   -------------------------------------  204.8/208.6 kB 958.4 kB/s eta 0:00:01
   -------------------------------------- 208.6/208.6 kB 793.5 kB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
    --------------------------------------- 0.1/6.9 MB 5.5 MB/s eta 0:00:02
    --------------------------------------- 0.1/6.9 MB 5.5 MB/s eta 0:00:02
    --------------------------------------- 0.1/6.9 MB 1.2 MB/s eta 0:00:06
   - -------------------------------------- 0.2/6.9 MB 1.5 MB/s eta 0:00:05
   - -------------------------------------- 0.2/6.9 MB 1.2 MB/s eta 0:00:06
   -- ------------------------------------- 0.4/6.9 MB 1.5 MB/s eta 0:00:05
   -- ------------------------------------- 0.4/6.9 MB 1.5 MB/s eta 0:00:05
   -- ------------------------------------- 0.4/6.9 MB 1.3 MB/s eta 0:00:05
   -- ------------------------------------- 0.5/6.9 MB 1.4 MB/s eta 0:00:05
   --- ------------------------------------ 0.5/6.9 MB 1.3 MB/s eta 0:00:05
   --- ------------------------------------ 0.6/6.9 MB 1.3 MB/s eta 0:00:05
   --- ------------------------------------ 0.6/6.9 MB 1.3 MB/s eta 0:00:05
   ---- ----------------------------------- 0.7/6.9 MB 1.3 MB/s eta 0:00:05
   ---- ----------------------------------- 0.8/6.9 MB 1.3 MB/s eta 0:00:05
   ---- ----------------------------------- 0.9/6.9 MB 1.3 MB/s eta 0:00:05
   ----- ---------------------------------- 0.9/6.9 MB 1.3 MB/s eta 0:00:05
   ----- ---------------------------------- 1.0/6.9 MB 1.3 MB/s eta 0:00:05
   ------ --------------------------------- 1.0/6.9 MB 1.3 MB/s eta 0:00:05
   ------ --------------------------------- 1.1/6.9 MB 1.3 MB/s eta 0:00:05
   ------ --------------------------------- 1.2/6.9 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.2/6.9 MB 1.3 MB/s eta 0:00:05
   ------- -------------------------------- 1.3/6.9 MB 1.3 MB/s eta 0:00:05
   ------- -------------------------------- 1.3/6.9 MB 1.4 MB/s eta 0:00:05
   -------- ------------------------------- 1.4/6.9 MB 1.4 MB/s eta 0:00:05
   -------- ------------------------------- 1.5/6.9 MB 1.3 MB/s eta 0:00:05
   -------- ------------------------------- 1.5/6.9 MB 1.3 MB/s eta 0:00:05
   --------- ------------------------------ 1.6/6.9 MB 1.4 MB/s eta 0:00:04
   --------- ------------------------------ 1.6/6.9 MB 1.3 MB/s eta 0:00:04
   ---------- ----------------------------- 1.8/6.9 MB 1.4 MB/s eta 0:00:04
   ---------- ----------------------------- 1.8/6.9 MB 1.4 MB/s eta 0:00:04
   ---------- ----------------------------- 1.9/6.9 MB 1.4 MB/s eta 0:00:04
   ----------- ---------------------------- 1.9/6.9 MB 1.4 MB/s eta 0:00:04
   ----------- ---------------------------- 2.0/6.9 MB 1.4 MB/s eta 0:00:04
   ----------- ---------------------------- 2.1/6.9 MB 1.4 MB/s eta 0:00:04
   ------------ --------------------------- 2.1/6.9 MB 1.4 MB/s eta 0:00:04
   ------------ --------------------------- 2.2/6.9 MB 1.4 MB/s eta 0:00:04
   ------------- -------------------------- 2.3/6.9 MB 1.4 MB/s eta 0:00:04
   ------------- -------------------------- 2.4/6.9 MB 1.4 MB/s eta 0:00:04
   ------------- -------------------------- 2.4/6.9 MB 1.4 MB/s eta 0:00:04
   -------------- ------------------------- 2.5/6.9 MB 1.4 MB/s eta 0:00:04
   -------------- ------------------------- 2.5/6.9 MB 1.4 MB/s eta 0:00:04
   --------------- ------------------------ 2.6/6.9 MB 1.4 MB/s eta 0:00:04
   --------------- ------------------------ 2.7/6.9 MB 1.4 MB/s eta 0:00:04
   --------------- ------------------------ 2.7/6.9 MB 1.4 MB/s eta 0:00:03
   ---------------- ----------------------- 2.8/6.9 MB 1.4 MB/s eta 0:00:03
   ---------------- ----------------------- 2.9/6.9 MB 1.4 MB/s eta 0:00:03
   ---------------- ----------------------- 2.9/6.9 MB 1.4 MB/s eta 0:00:03
   ----------------- ---------------------- 3.0/6.9 MB 1.4 MB/s eta 0:00:03
   ----------------- ---------------------- 3.1/6.9 MB 1.4 MB/s eta 0:00:03
   ------------------ --------------------- 3.2/6.9 MB 1.4 MB/s eta 0:00:03
   ------------------ --------------------- 3.2/6.9 MB 1.4 MB/s eta 0:00:03
   ------------------- -------------------- 3.3/6.9 MB 1.4 MB/s eta 0:00:03
   ------------------- -------------------- 3.4/6.9 MB 1.4 MB/s eta 0:00:03
   ------------------- -------------------- 3.4/6.9 MB 1.4 MB/s eta 0:00:03
   -------------------- ------------------- 3.5/6.9 MB 1.4 MB/s eta 0:00:03
   -------------------- ------------------- 3.5/6.9 MB 1.4 MB/s eta 0:00:03

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

envoyer un JSON “pro”

In [5]:
import json, time, random
from kafka import KafkaProducer

producer = KafkaProducer(
    bootstrap_servers="localhost:9092",
    value_serializer=lambda v: json.dumps(v).encode("utf-8")
)

def fake_bbox():
    x = random.randint(50, 200)
    y = random.randint(50, 200)
    w = random.randint(80, 140)
    h = random.randint(80, 140)
    return x, y, w, h

emotions = ["happy", "neutral", "sad", "angry", "surprise"]

for frame_id in range(1, 11):
    x, y, w, h = fake_bbox()
    event = {
        "source_id": "cam_01",
        "frame_id": frame_id,
        "face_id": 1,
        "producer_ts": time.time(),  # epoch seconds
        "emotion": random.choice(emotions),
        "score": round(random.uniform(0.55, 0.98), 2),
        "bbox_x": x, "bbox_y": y, "bbox_w": w, "bbox_h": h
    }
    producer.send("test_topic", event)
    time.sleep(0.2)

producer.flush()
print("✅ sent 10 pro events")

✅ sent 10 pro events

In [4]:
import json, time, random
from kafka import KafkaProducer

producer = KafkaProducer(
    bootstrap_servers="localhost:9092",
    value_serializer=lambda v: json.dumps(v).encode("utf-8")
)

emotions = ["happy", "neutral", "sad", "angry", "surprise"]

def fake_bbox():
    x = random.randint(40, 250)
    y = random.randint(40, 200)
    w = random.randint(80, 160)
    h = random.randint(80, 160)
    return x, y, w, h

for frame_id in range(1, 21):
    x, y, w, h = fake_bbox()
    event = {
        "source_id": "cam_01",
        "frame_id": frame_id,
        "face_id": 1,
        "producer_ts": time.time(),   # epoch seconds (float)
        "emotion": random.choice(emotions),
        "score": round(random.uniform(0.55, 0.98), 2),
        "bbox_x": x, "bbox_y": y, "bbox_w": w, "bbox_h": h
    }
    producer.send("test_topic", event)
    time.sleep(0.15)

producer.flush()
print("✅ sent 20 pro events")

✅ sent 20 pro events

In [3]:
import pandas as pd
df_v2 = pd.read_parquet("data/parquet_events_v2")
df_v2.tail(10)

Empty DataFrame
Columns: [source_id, frame_id, face_id, producer_ts, emotion, score, bbox_x, bbox_y, bbox_w, bbox_h, spark_ts, event_ts, e2e_latency_ms, processing_time_ms]
Index: []

In [1]:
import onnxruntime as ort
print("ORT version:", ort.__version__)
print("Available providers:", ort.get_available_providers())

ModuleNotFoundError: No module named 'onnxruntime'